### PR TITLE
Addition of PIP-33: Lock Account Address

### PR DESCRIPTION
**Pull request by Mr-HoDL58**
Addition of PIP-33

### CODE REVIEW

**Comment by Ja7ad** [comment]
Please fix linter issues: https://github.com/pactus-project/PIPs/actions/runs/11094365532/job/30821767594?pr=179

**Comment by Mr-HoDL58** [comment]
@Ja7ad im not sure how.

**Comment by Ja7ad** [comment]
> @Ja7ad im not sure how. 
> 

Please check logs: https://github.com/pactus-project/PIPs/actions/runs/11094365532/job/30821767594

**Comment by Mr-HoDL58** [comment]
@Ja7ad i have looked but it also shows things for PIP 32 I synced my repo so not sure how the 32 exists there.

**Comment by Mr-HoDL58** [comment]
@Ja7ad I have fixed all the linting but i have no clue about the html proofer.

**Pull request merged**
